export const queryKeys = {
  me: ['me'] as const,
  adminUsersBase: ['admin-users'] as const,
  adminUsers: (query: Record<string, unknown> = {}) => [...queryKeys.adminUsersBase, query] as const,
  regions: ['regions'] as const,
  districts: (regionId: string) => ['districts', regionId] as const,
  schools: (districtId: string) => ['schools', districtId] as const,
  subjects: ['subjects'] as const,
  adminSubjects: ['admin-subjects'] as const,
  adminTestsBase: ['admin-tests'] as const,
  adminTests: (query: Record<string, unknown> = {}) => [...queryKeys.adminTestsBase, query] as const,
  adminTest: (testId: string) => ['admin-test', testId] as const,
  publishedTests: (subjectId?: string) => ['published-tests', subjectId ?? ''] as const,
  myAttemptsBase: ['my-attempts'] as const,
  attempt: (attemptId: string) => ['attempt', attemptId] as const,
  adminUser: (userId: string) => ['admin-user', userId] as const,
  adminUserAttempts: (userId: string) => ['admin-user-attempts', userId] as const,
  ratingsBase: ['ratings'] as const,
  ratings: (query: Record<string, unknown> = {}) => [...queryKeys.ratingsBase, query] as const,
  topRating: (query: Record<string, unknown> = {}) => ['top-rating', query] as const,
  myRating: ['my-rating'] as const,
  ratingSettings: ['rating-settings'] as const,
  myCertificates: ['my-certificates'] as const,
  certificate: (certificateId: string) => ['certificate', certificateId] as const,
  certificateTemplate: ['certificate-template'] as const,
  notifications: ['notifications'] as const,
  notificationTemplates: ['notification-templates'] as const,
  search: (q: string) => ['search', q] as const,
  teacherDashboard: ['teacher-dashboard'] as const,
  adminDashboard: ['admin-dashboard'] as const,
};
