/**
 * @file Automatically generated by barrelsby.
 */

export * from "./auth.controller";
export * from "./aws.controller";
export * from "./geo.controller";
export * from "./health.controller";
export * from "./question.controller";
export * from "./rating.controller";
export * from "./subject.controller";
export * from "./test-attempt.controller";
export * from "./test.controller";
export * from "./user.controller";
