/**
 * @file Automatically generated by barrelsby.
 */

export * from "./auth.controller";
export * from "./aws.controller";
export * from "./certificate.controller";
export * from "./dashboard.controller";
export * from "./geo.controller";
export * from "./health.controller";
export * from "./legal.controller";
export * from "./notification.controller";
export * from "./question.controller";
export * from "./rating.controller";
export * from "./search.controller";
export * from "./subject.controller";
export * from "./test-attempt.controller";
export * from "./test.controller";
export * from "./user.controller";
